// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19L4rk6BLJ1Cu8zY1jIk9CQIEhFWhIbs',
    appId: '1:549857820910:web:3527fad9c8878f097033ff',
    messagingSenderId: '549857820910',
    projectId: 'yo-do-flutter-app',
    authDomain: 'yo-do-flutter-app.firebaseapp.com',
    storageBucket: 'yo-do-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OyP-VsysjSZN2i7i75yCJx9oEUZKOcA',
    appId: '1:549857820910:android:eb4ed8eb465b32397033ff',
    messagingSenderId: '549857820910',
    projectId: 'yo-do-flutter-app',
    storageBucket: 'yo-do-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGXF37YAhJ2vQ1Of0_TLzUcqSbOHU7fZM',
    appId: '1:549857820910:ios:8d45676352a656647033ff',
    messagingSenderId: '549857820910',
    projectId: 'yo-do-flutter-app',
    storageBucket: 'yo-do-flutter-app.appspot.com',
    iosBundleId: 'com.example.finalAssingment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGXF37YAhJ2vQ1Of0_TLzUcqSbOHU7fZM',
    appId: '1:549857820910:ios:8d45676352a656647033ff',
    messagingSenderId: '549857820910',
    projectId: 'yo-do-flutter-app',
    storageBucket: 'yo-do-flutter-app.appspot.com',
    iosBundleId: 'com.example.finalAssingment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19L4rk6BLJ1Cu8zY1jIk9CQIEhFWhIbs',
    appId: '1:549857820910:web:76d8e1a49871c1eb7033ff',
    messagingSenderId: '549857820910',
    projectId: 'yo-do-flutter-app',
    authDomain: 'yo-do-flutter-app.firebaseapp.com',
    storageBucket: 'yo-do-flutter-app.appspot.com',
  );

}